---
biddingEnabled: true
prebidEnabled: true
timeout: 1500
amazonPubId: 3176
priceGranularity: dense
defaultConfig:
  openx:
    delDomain: sbnationbidder-d.openx.net
    unit: 538623514
  rubicon:
    accountId: 7470
    position: btf
    siteId: 40760
    zoneId: 185758
  rubiconLite:
    accountId: 18288
    siteId: 193902
    sizes: [213, 270, 271, 272]
    position: btf
  consumable:
    networkId: 9969
    siteId: 1039096
  rubi__mm:
    accountId: 21670
    siteId: 294140
    zoneId: 1480270
    zoneName: "Eater_MediaMath DC"
  rubi__ttd:
    accountId: 21670
    siteId: 294142
    zoneName: "Eater_TTD DC"
    zoneId: 1480296
  teads:
    pageId: 104316
  usersync:
    userIds:
      - name: "unifiedId"
        params:
          url: "https://match.adsrvr.org/track/rid?ttd_pid=gs8reto&fmt=json"
        storage:
          type: "cookie"
          name: "pbjs-unifiedid"
          expires: 14
        syncDelay: 3000
prelude:
  trustx:
    uid: 2663
reskin:
  trustx:
    uid: 2664
desktop_leaderboard_variable:
  trustx:
    uid: 2665
  appnexus:
    placementId: 9887399
  ix:
    siteId: 186869
  rubicon:
    position: atf
  triplelift:
    inventoryCode: eater_main_leaderboard
  consumable:
    unitId: 5494
    unitName: cnsmbl-audio-728x90-slider
medium_rectangle_variable:
  trustx:
    uid: 2666
  appnexus:
    placementId: 9887400
  ix:
    siteId: 186870
  rubicon:
    position: atf
  triplelift:
    inventoryCode: eater_300x250_desktop
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
btf_medium_rectangle_variable:
  trustx:
    uid: 2668
  appnexus:
    placementId: 9887402
  ix:
    siteId: 186871
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
desktop_article_medrec_dynamic:
  trustx:
    uid: 2669
  appnexus:
    placementId: 11807789
  ix:
    siteId: 212942
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
btf_leaderboard_variable:
  trustx:
    uid: 2670
  appnexus:
    placementId: 9887403
  ix:
    siteId: 186872
  consumable:
    unitId: 5494
    unitName: cnsmbl-audio-728x90-slider
native_ad_latest:
  trustx:
    uid: 2671
native_ad_ymal_link:
  trustx:
    uid: 2672
mobile_leaderboard:
  trustx:
    uid: 2673
  appnexus:
    placementId: 9887404
  ix:
    siteId: 186878
  rubicon:
    position: atf
  triplelift:
    inventoryCode: eater_300x250_leaderboard_mobile
  consumable:
    unitId: 5510
    unitName: cnsmbl-audio-320x50-slider
mobile_article_body:
  teads:
    placementId: 112929
  trustx:
    uid: 2674
  appnexus:
    placementId: 11807786
  ix:
    siteId: 212939
  rubiconLite:
    zoneId: 944790
  consumable:
    unitId: 5502
    unitName: cnsmbl-audio-300x250-slider
native_ad_mobile:
  teads:
    placementId: 112929
  trustx:
    uid: 2675
  consumable:
    unitId: 5510
    unitName: cnsmbl-audio-320x50-slider
mobile_article_body_med_rec_dynamic:
  teads:
    placementId: 112929
  trustx:
    uid: 2676
  appnexus:
    placementId: 11807788
  ix:
    siteId: 212941
  rubiconLite:
    zoneId: 944790
  consumable:
    unitId: 5502
    unitName: cnsmbl-audio-300x250-slider
mobile_footer:
  trustx:
    uid: 2677
  appnexus:
    placementId: 9887406
  ix:
    siteId: 186880
  consumable:
    unitId: 5510
    unitName: cnsmbl-audio-320x50-slider
tablet_leaderboard:
  trustx:
    uid: 2678
  appnexus:
    placementId: 9887407
  ix:
    siteId: 186874
  rubicon:
    position: atf
  consumable:
    unitId: 5494
    unitName: cnsmbl-audio-728x90-slider
tablet_medium_rectangle:
  trustx:
    uid: 2679
  appnexus:
    placementId: 9887408
  ix:
    siteId: 186875
  rubicon:
    position: atf
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
tablet_btf_leaderboard:
  trustx:
    uid: 2680
  appnexus:
    placementId: 9887410
  ix:
    siteId: 0
  consumable:
    unitId: 5494
    unitName: cnsmbl-audio-728x90-slider
native_ad_content_link:
  trustx:
    uid: 2681
hub_river_leaderboard:
  trustx:
    uid: 2682
  appnexus:
    placementId: 11807790
  ix:
    siteId: 212943
  rubiconLite:
    zoneId: 944790
  consumable:
    unitId: 5494
    unitName: cnsmbl-audio-728x90-slider
hub_river_med_rec:
  trustx:
    uid: 2684
  appnexus:
    placementId: 11807791
  ix:
    siteId: 212944
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
mobile_med_rec_athena:
  trustx:
    uid: 2685
  appnexus:
    placementId: 9887405
  ix:
    siteId: 186879
  rubicon:
    position: atf
  triplelift:
    inventoryCode: eater_300x250_midcontent_mobile
  rubiconLite:
    zoneId: 944790
    position: atf
  consumable:
    unitId: 5502
    unitName: cnsmbl-audio-300x250-slider
athena:
  appnexus:
    placementId: 9887401
  ix:
    siteId: 186873
  rubicon:
    position: atf
  rubiconLite:
    zoneId: 944790
    position: atf
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
btf_tablet_medium_rectangle:
  appnexus:
    placementId: 9887409
  ix:
    siteId: 186876
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
in_map:
  appnexus:
    placementId: 9887402
  ix:
    siteId: 186871
  rubiconLite:
    zoneId: 944790
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
desktop_article_body:
  teads:
    placementId: 112929
  appnexus:
    placementId: 11807787
  ix:
    siteId: 212940
  rubiconLite:
    zoneId: 944790
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
athena_features:
  appnexus:
    placementId: 11807792
  ix:
    siteId: 212945
  rubiconLite:
    zoneId: 944790
  consumable:
    unitId: 5478
    unitName: cnsmbl-audio-300x250-slider
  teads:
    placementId: 112929
athena_features_dynamic:
  appnexus:
    placementId: 11807793
  ix:
    siteId: 212946
  rubiconLite:
    zoneId: 944790
  consumable:
    unitId: 5502
    unitName: cnsmbl-audio-300x250-slider
  teads:
    placementId: 112929
