---
biddingEnabled: false
prebidEnabled: false
rubiconDemandManagerEnabled: false
timeout: 1000
amazonPubId: 3176
priceGranularity: dense
defaultConfig:
  openx:
    delDomain: sbnationbidder-d.openx.net
  rubicon:
    accountId: 7470
    position: btf
  rubiconLite:
    accountId: 18288
    siteId: 193902
    sizes: [213, 270, 271, 272]
    position: btf
  consumable:
    networkId: 9969
    siteId: 1039096
  rubi__mm:
    accountId: 21670
    siteId: 294140
    zoneId: 1480258
    zoneName: "SBNation_MediaMath DC"
  rubi__ttd:
    accountId: 21670
    siteId: 294142
    zoneName: "SBNation_TTD DC"
    zoneId: 1480284
  usersync:
    userIds:
      - name: "unifiedId"
        params:
          url: "https://match.adsrvr.org/track/rid?ttd_pid=gs8reto&fmt=json"
        storage:
          type: "cookie"
          name: "pbjs-unifiedid"
          expires: 14
        syncDelay: 3000
prelude:
  trustx:
    uid: 2663
  consumable:
    unitId: 7423
    unitName: cnsmbl-video-970x250
reskin:
  trustx:
    uid: 2664
desktop_leaderboard_variable:
  trustx:
    uid: 2665
medium_rectangle_variable:
  trustx:
    uid: 2666
btf_medium_rectangle_variable:
  trustx:
    uid: 2668
desktop_article_medrec_dynamic:
  trustx:
    uid: 2669
btf_leaderboard_variable:
  trustx:
    uid: 2670
native_ad_latest:
  trustx:
    uid: 2671
native_ad_ymal_link:
  trustx:
    uid: 2672
mobile_leaderboard:
  trustx:
    uid: 2673
mobile_article_body:
  trustx:
    uid: 2674
native_ad_mobile:
  trustx:
    uid: 2675
mobile_article_body_med_rec_dynamic:
  trustx:
    uid: 2676
mobile_footer:
  trustx:
    uid: 2677
tablet_leaderboard:
  trustx:
    uid: 2678
tablet_medium_rectangle:
  trustx:
    uid: 2679
tablet_btf_leaderboard:
  trustx:
    uid: 2680
native_ad_content_link:
  trustx:
    uid: 2681
hub_river_leaderboard:
  trustx:
    uid: 2682
hub_river_med_rec:
  trustx:
    uid: 2684
mobile_med_rec_athena:
  trustx:
    uid: 2685
