---
- behavior: merge
  remove:
  - prelude
  - site_sponsorship_logo_white
  - site_sponsorship_logo_color
  - site_sponsorship_logo_mobile_white
  - site_sponsorship_logo_mobile_color
  - native_ad_latest
  - native_ad_video
  - native_ad_ymal_link
  - native_ad_linkset_link
  - native_ad_content_link
  - native_ad_module
  - branded_content_feedback_form
  - buy_button

- name: outbrain
  type: outbrain
  widgetId: AR_1
  selector: body:not(.l-hub-page) .l-segment:not(.l-feature) .l-sidebar-fixed:not(.l-article-body-segment)
  maxSlots: 1
  watcherEligible: false

- name: editorially_placed_athena_desktop
  sizes:
  - [1030, 590]
  - [728, 90]
  - size: [1060, 610]
    filters:
      containerWidth:
        min: 1060
  - size: [620, 366]
    filters:
      containerWidth:
        max: 1059
  - size: [1060, 619]
    filters:
      containerWidth:
        min: 1060
  - size: [1060, 694]
    filters:
      containerWidth:
        min: 1060

- name: editorially_placed_athena_mobile
  sizes:
  - [300, 250]
  - [300, 250v]
  - [1030, 590]
  - [325, 508]
  - [325, 203]
  - [325, 236]
  - [325, 204]

- name: athena_article
  prebidName: desktop_athena_dynamic
  sizes:
  - [728, 90]
  - [970, 250]
  - [1030, 590]
  - [620, 366]
  - [620, 371]
  - [620, 415]

- name: medium_rectangle_short
  prebidName: desktop_article_medrec_dynamic
  watcherEligible: false
  sizes:
  - [300, 250]
  - [300, 250v]
  - [300, 600]

- name: btf_medium_rectangle_variable_article
  prebidName: medium_rectangle_variable
  watcherEligible: false
  refreshRate: 30

- name: mobile_article_body_med_rec_dynamic
  watcherEligible: false
  prebidName: mobile_med_rec_athena
  sizes:
  - [300, 250]
  - [300, 250v]
  - [1030, 590]
  - [325, 508]
  - [325, 203]
  - [325, 236]
  - [325, 204]

- name: athena_features_desktop
  watcherEligible: false
  prebidName: desktop_athena_dynamic
  sizes:
  - [728, 90]
  - [970, 250]
  - [970, 90]
  - [1030, 590]
  - [620, 366]
  - [620, 371]
  - [620, 415]

- name: athena_features_dynamic_mobile
  watcherEligible: false
  prebidName: mobile_med_rec_athena
  sizes:
  - [1030, 590]
  - [325, 508]
  - [300, 250]
  - [300, 250v]
  - [300, 265]
  - [325, 203]
  - [325, 236]
  - [325, 204]

- name: athena_features_mobile
  watcherEligible: false
  prebidName: mobile_med_rec_athena
  sizes:
  - [1030, 590]
  - [325, 508]
  - [300, 250]
  - [300, 250v]
  - [300, 265]
  - [325, 203]
  - [325, 236]
  - [325, 204]

- name: desktop_feature_body_dynamic
  watcherEligible: false
  prebidName: desktop_dynamic
  sizes:
  - [728, 90]
  - [300, 250]
  - [300, 250v]
  - [620, 366]
  - [1030, 590]

- name: desktop_feature_body
  watcherEligible: false
  prebidName: desktop_article_body
  sizes:
  - [728, 90]
  - [620, 366]
  - [1030, 590]

- name: athena_hub
  prebidName: desktop_athena_dynamic
  sizes:
  - [728, 90]
  - [1030, 590]
  - [970, 90]
  - size: [1060, 610]
    filters:
      containerWidth:
        min: 1060
  - size: [620, 366]
    filters:
      containerWidth:
        max: 1059
  - size: [1060, 619]
    filters:
      containerWidth:
        min: 1060
  - size: [1060, 694]
    filters:
      containerWidth:
        min: 1060
  - size: [970, 250]
    filters:
      viewportWidth:
        min: 970

- name: editorially_placed_leaderboard
  prebidName: desktop_article_body

- name: package_cover_ad
  watcherEligible: false
  prebidName: desktop_leaderboard_variable
  sizes:
  - [728, 90]
  - [970, 250]
  - [970, 90]
  - [1020, 90]
  - [1030, 590]
  - size: [1060, 610]
    filters:
      containerWidth:
        min: 1060
  - size: [620, 366]
    filters:
      containerWidth:
        max: 1059
  - size: [1060, 619]
    filters:
      containerWidth:
        min: 1060
  - size: [1060, 694]
    filters:
      containerWidth:
        min: 1060

- name: medium_rectangle_variable_section_front
  prebidName: medium_rectangle_variable
  watcherEligible: false
  selector: .c-section-front-block--has_ad .c-section-front-block__ad
  sizes:
  - [300, 250]
  - [300, 250v]
  - [300, 600]
  holdSize: [300, 250]
  insertion: inside
  filters:
    viewportWidth:
      min: 881

- name: desktop_leaderboard_variable
  sizes:
  - [728, 90]
  - [970, 250]
  - [970, 90]
  - [1020, 90]
  - [1030, 590]
  - [620, 366]

- name: tablet_leaderboard
  watcherEligible: false

- name: mobile_leaderboard_hub
  watcherEligible: false
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [300, 50]

- name: mobile_leaderboard_group
  watcherEligible: false
  sizes:
  - [320, 50]
  - [300, 50]
  - [300, 250]
  - [300, 250v]

- name: package_cover_ad_mobile
  prebidName: mobile_leaderboard
  watcherEligible: false
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [1030, 590]
  - [325, 508]
  - [325, 203]
  - [325, 236]
  - [325, 204]
  - [1020, 90]
  - [300, 50]

- name: btf_leaderboard_variable
  prebidName: desktop_leaderboard_variable
  watcherEligible: false
  sizes:
  - [728, 90]
  - [1020, 90]
  - [970, 250]

- name: tablet_btf_leaderboard
  watcherEligible: false

- name: mobile_footer
  watcherEligible: false
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [325, 203]
  - [325, 236]
  - [325, 204]
  - [300, 50]

- name: package_mobile_footer
  prebidName: mobile_footer
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [1030, 590]
  - [325, 508]
  - [325, 203]
  - [325, 236]
  - [325, 204]
  - [300, 50]

- name: mobile_feature_body
  prebidName: mobile_leaderboard
  sizes:
  - [300, 250]
  - [300, 250v]
  - [325, 508]
  - [325, 203]
  - [325, 236]
  - [325, 204]
  - [320, 50]
  - [1030, 590]
  - [300, 50]

- name: mobile_leaderboard
  watcherEligible: false
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [300, 50]

- name: gift_guide_leaderboard_mobile
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [1030, 590]
  - [300, 50]

- name: storystream_top_leaderboard_mobile
  prebidName: mobile_leaderboard
  sizes:
  - [320, 50]
  - [300, 50]
  watcherEligible: false

- name: storystream_bottom_leaderboard_variable_mobile
  prebidName: mobile_leaderboard
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [1030, 590]
  - [325, 508]
  - [325, 203]
  - [325, 236]
  - [325, 204]
  - [300, 50]

- name: storystream_river_leaderboard_variable_mobile
  prebidName: mobile_leaderboard
  sizes:
  - [320, 50]
  - [300, 250]
  - [300, 250v]
  - [300, 50]
  watcherEligible: false

- name: desktop_article_medrec_dynamic
  watcherEligible: false

- name: medium_rectangle_variable
  watcherEligible: false

- name: btf_medium_rectangle_variable_hub
  watcherEligible: false
  refreshRate: 30

- name: in_map_legacy
  watcherEligible: false

- name: mapstack_sponsorship
  watcherEligible: false

- name: article_sponsorship
  sizes:
  - [210, 40]
  selector: body.entry_layout_unison_main .c-social-buttons
  insertion: before
  watcherEligible: false

- name: hub_sponsorship
  watcherEligible: false
  sizes:
  - [210, 40]

- name: out_of_page
  selector: .c-footer
  sizes:
  - [1, 1]
  watcherEligible: false
  prebidEligible: false
  outOfPage: true
  insertion: after

# Within the river on home, hub, group, and article pages - This is the GAM Native River Ad for CST
- name: native_river
  className: m-ad__native_river
  selector: .l-hub-page .river-segment-0 .c-compact-river__entry:nth-child(3), .l-group-page .river-segment-0 .c-compact-river__entry:nth-child(3), .entry_layout_unison_main .c-compact-river .c-compact-river__entry:nth-child(4)
  sizes:
  - fluid
  - [1, 3]
  prebidEligible: false
  refreshEligible: false
  watcherEligible: false
