---
biddingEnabled: true
prebidEnabled: true
timeout: 1500
amazonPubId: 3176
priceGranularity: dense
defaultConfig:
  openx:
    delDomain: sbnationbidder-d.openx.net
    unit: 538623520
  rubicon:
    accountId: 7470
    position: btf
    siteId: 40684
    zoneId: 185818
  rubiconLite:
    accountId: 18288
    siteId: 193902
    sizes: [213, 270, 271, 272]
    position: btf
  consumable:
    networkId: 9969
    siteId: 1039096
  teads:
    pageId: 104313
  rubi__mm:
    accountId: 21670
    siteId: 294140
    zoneName: "TheVerge_MediaMath DC"
    zoneId: 1480264
  rubi__ttd:
    accountId: 21670
    siteId: 294142
    zoneName: "TheVerge_TTD DC"
    zoneId: 1480290
  usersync:
    userIds:
      - name: "unifiedId"
        params:
          url: "https://match.adsrvr.org/track/rid?ttd_pid=gs8reto&fmt=json"
        storage:
          type: "cookie"
          name: "pbjs-unifiedid"
          expires: 14
        syncDelay: 3000
prelude:
  trustx:
    uid: 2663
reskin:
  trustx:
    uid: 2664
desktop_leaderboard_variable:
  trustx:
    uid: 2665
  appnexus:
    placementId: 9885469
  ix:
    siteId: 185962
  rubicon:
    position: atf
  triplelift:
    inventoryCode: theverge_leaderboard_desktop
  consumable:
    unitId: 5499
    unitName: cnsmbl-audio-728x90-slider
medium_rectangle_variable:
  trustx:
    uid: 2666
  appnexus:
    placementId: 9885470
  ix:
    siteId: 185963
  rubicon:
    position: atf
  triplelift:
    inventoryCode: theverge_300x250_desktop
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
btf_medium_rectangle_variable:
  trustx:
    uid: 2668
  appnexus:
    placementId: 9885472
  ix:
    siteId: 185966
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
desktop_article_medrec_dynamic:
  trustx:
    uid: 2669
  appnexus:
    placementId: 11807780
  ix:
    siteId: 213003
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
btf_leaderboard_variable:
  trustx:
    uid: 2670
  appnexus:
    placementId: 9885490
  ix:
    siteId: 185965
  consumable:
    unitId: 5499
    unitName: cnsmbl-audio-728x90-slider
native_ad_latest:
  trustx:
    uid: 2671
native_ad_ymal_link:
  trustx:
    uid: 2672
mobile_leaderboard:
  trustx:
    uid: 2673
  appnexus:
    placementId: 9885473
  ix:
    siteId: 185971
  rubicon:
    position: atf
  triplelift:
    inventoryCode: theverge_300x250_leaderboard_mobile
  consumable:
    unitId: 5516
    unitName: cnsmbl-audio-320x50-slider
mobile_article_body:
  teads:
    placementId: 112923
  trustx:
    uid: 2674
  appnexus:
    placementId: 11807777
  ix:
    siteId: 213000
  rubiconLite:
    zoneId: 944784
  consumable:
    unitId: 5507
    unitName: cnsmbl-audio-300x250-slider
native_ad_mobile:
  teads:
    placementId: 112923
  trustx:
    uid: 2675
  consumable:
    unitId:
    unitName:
mobile_article_body_med_rec_dynamic:
  teads:
    placementId: 112923
  trustx:
    uid: 2676
  appnexus:
    placementId: 11807779
  ix:
    siteId: 213002
  rubiconLite:
    zoneId: 944784
  consumable:
    unitId: 5507
    unitName: cnsmbl-audio-300x250-slider
mobile_footer:
  trustx:
    uid: 2677
  appnexus:
    placementId: 9885475
  ix:
    siteId: 185972
  consumable:
    unitId: 5516
    unitName: cnsmbl-audio-320x50-slider
tablet_leaderboard:
  trustx:
    uid: 2678
  appnexus:
    placementId: 9885477
  ix:
    siteId: 185968
  rubicon:
    position: atf
  consumable:
    unitId: 5499
    unitName: cnsmbl-audio-728x90-slider
tablet_medium_rectangle:
  trustx:
    uid: 2679
  appnexus:
    placementId: 9885478
  ix:
    siteId: 185969
  rubicon:
    position: atf
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
tablet_btf_leaderboard:
  trustx:
    uid: 2680
  appnexus:
    placementId: 9885480
  ix:
    siteId: 185970
  consumable:
    unitId: 5499
    unitName: cnsmbl-audio-728x90-slider
native_ad_content_link:
  trustx:
    uid: 2681
hub_river_leaderboard:
  trustx:
    uid: 2682
  appnexus:
    placementId: 11807782
  ix:
    siteId: 213004
  rubiconLite:
    zoneId: 944784
  consumable:
    unitId: 5499
    unitName: cnsmbl-audio-728x90-slider
hub_river_med_rec:
  trustx:
    uid: 2684
  appnexus:
    placementId: 11807783
  ix:
    siteId: 213005
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
mobile_med_rec_athena:
  trustx:
    uid: 2685
  appnexus:
    placementId: 9885474
  ix:
    siteId: 186845
  rubicon:
    position: atf
  triplelift:
    inventoryCode: theverge_300x250_mobile
  rubiconLite:
    zoneId: 944784
    position: atf
  consumable:
    unitId: 5507
    unitName: cnsmbl-audio-300x250-slider
athena:
  appnexus:
    placementId: 9885471
  ix:
    siteId: 185967
  rubicon:
    position: atf
  rubiconLite:
    zoneId: 944784
    position: atf
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
btf_tablet_medium_rectangle:
  appnexus:
    placementId: 9885479
  ix:
    siteId: 186844
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
desktop_article_body:
  teads:
    placementId: 112923
  appnexus:
    placementId: 11807778
  ix:
    siteId: 213001
  rubiconLite:
    zoneId: 944784
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
in_map:
  appnexus:
    placementId: 11807781
  ix:
    disabled: true
  rubiconLite:
    zoneId: 944784
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
athena_features:
  appnexus:
    placementId: 11807784
  ix:
    siteId: 213006
  rubiconLite:
    zoneId: 944784
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
  teads:
    placementId: 112923
athena_features_dynamic:
  appnexus:
    placementId: 11807785
  ix:
    siteId: 213007
  rubiconLite:
    zoneId: 944784
  consumable:
    unitId: 5483
    unitName: cnsmbl-audio-300x250-slider
  teads:
    placementId: 112923
