nodeResize:
  - targetSelectors: ['#comments']
    observe: minHeight
    observeLimit: 60
    insert:
      includedSlots: ['comments_medium_rectangle', 'comments_medium_rectangle_short']
    breakpointMin: 728

experiments:
- id: 1
  start_date: '2020-06-04'
  end_date: '2020-06-11'
  share: 0.5  
  variations:
  - id: 0
    config:
      lazy_bid: false 
  - id: 1
    config:
      lazy_bid: true
          
permutiveEnabled: true
