---
- behavior: replace

- name: mobile_article_body_med_rec_dynamic
  selector: "#arizona-primary-results #block1, #arizona-primary-results #block4, #florida-primary-results #block5, #florida-primary-results #block5, #florida-primary-results #block10, #oklahoma-primary-runoff-results .text-bar:last-child"
  sizes:
  - [300, 250]
  - [300, 250v]
  - [320, 50]
  previewHoldSize: [300, 250]
  maxSlots: 3
  insertion: after
  filters:
    spacing:
      before: 150
    viewportWidth:
      max: 779

- name: athena
  selector: "#arizona-primary-results #block1, #arizona-primary-results #block4, #florida-primary-results #block5, #florida-primary-results #block5, #florida-primary-results #block10, #oklahoma-primary-runoff-results .text-bar:last-child"
  sizes:
  - [1030, 590]
  - [728, 90]
  holdSize: [728, 295]
  insertion: after
  maxSlots: 3
  filters:
    viewportWidth:
      min: 780
