---
biddingEnabled: true
prebidEnabled: true
timeout: 1500
amazonPubId: 3176
defaultConfig:
  openx:
    delDomain: sbnationbidder-d.openx.net
    unit: 538623521
  rubicon:
    accountId: 7470
    position: btf
    siteId: 42504
    zoneId: 185834
  rubiconLite:
    accountId: 18288
    siteId: 193902
    sizes: [213, 270, 271, 272]
    position: btf
  consumable:
    networkId: 9969
    siteId: 1039096
  teads:
    pageId: 104311
  rubi__mm:
    accountId: 21670
    siteId: 294140
    zoneName: "Vox.com_MediaMath DC"
    zoneId: 1480260
  rubi__ttd:
    accountId: 21670
    siteId: 294142
    zoneName: "Vox.com_TTD DC"
    zoneId: 1480286
  usersync:
    userIds:
      - name: "unifiedId"
        params:
          url: "https://match.adsrvr.org/track/rid?ttd_pid=gs8reto&fmt=json"
        storage:
          type: "cookie"
          name: "pbjs-unifiedid"
          expires: 14
        syncDelay: 3000
prelude:
  trustx:
    uid: 2663
reskin:
  trustx:
    uid: 2664
desktop_leaderboard_variable:
  trustx:
    uid: 2665
  appnexus:
    placementId: 9883542
  ix:
    siteId: 186846
  rubicon:
    position: atf
  triplelift:
    inventoryCode: vox_main_leaderboard
  consumable:
    unitId: 5500
    unitName: cnsmbl-audio-728x90-slider
medium_rectangle_variable:
  trustx:
    uid: 2666
  appnexus:
    placementId: 9883543
  ix:
    siteId: 186847
  rubicon:
    position: atf
  triplelift:
    inventoryCode: vox_300x250_desktop
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
btf_medium_rectangle_variable:
  trustx:
    uid: 2668
  appnexus:
    placementId: 9883545
  ix:
    siteId: 186848
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
desktop_article_medrec_dynamic:
  trustx:
    uid: 2669
  appnexus:
    placementId: 11726795
  ix:
    siteId: 213011
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
btf_leaderboard_variable:
  trustx:
    uid: 2670
  appnexus:
    placementId: 9883546
  ix:
    siteId: 186849
  consumable:
    unitId: 5500
    unitName: cnsmbl-audio-728x90-slider
native_ad_latest:
  trustx:
    uid: 2671
native_ad_ymal_link:
  trustx:
    uid: 2672
mobile_leaderboard:
  trustx:
    uid: 2673
  appnexus:
    placementId: 9883556
  ix:
    siteId: 186855
  rubicon:
    position: atf
  triplelift:
    inventoryCode: vox_leaderboard_300x250_mobile
  consumable:
    unitId: 5517
    unitName: cnsmbl-audio-320x50-slider
mobile_article_body:
  teads:
    placementId: 112919
  trustx:
    uid: 2674
  appnexus:
    placementId: 11807662
  ix:
    siteId: 213008
  rubiconLite:
    zoneId: 968556
  consumable:
    unitId: 5508
    unitName: cnsmbl-audio-300x250-slider
native_ad_mobile:
  teads:
    placementId: 112919
  trustx:
    uid: 2675
  consumable:
    unitId: 5517
    unitName: cnsmbl-audio-300x250-slider
mobile_article_body_med_rec_dynamic:
  teads:
    placementId: 112919
  trustx:
    uid: 2676
  appnexus:
    placementId: 11726794
  ix:
    siteId: 213010
  rubiconLite:
    zoneId: 968556
  consumable:
    unitId: 5508
    unitName: cnsmbl-audio-300x250-slider
mobile_footer:
  trustx:
    uid: 2677
  appnexus:
    placementId: 9883559
  ix:
    siteId: 186857
  consumable:
    unitId: 5517
    unitName: cnsmbl-audio-320x50-slider
tablet_leaderboard:
  trustx:
    uid: 2678
  appnexus:
    placementId: 9883548
  ix:
    siteId: 186851
  rubicon:
    position: atf
  consumable:
    unitId: 5500
    unitName: cnsmbl-audio-728x90-slider
tablet_medium_rectangle:
  trustx:
    uid: 2679
  appnexus:
    placementId: 9883549
  ix:
    siteId: 186852
  rubicon:
    position: atf
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
tablet_btf_leaderboard:
  trustx:
    uid: 2680
  appnexus:
    placementId: 9883551
  ix:
    siteId: 186854
  consumable:
    unitId: 5500
    unitName: cnsmbl-audio-728x90-slider
native_ad_content_link:
  trustx:
    uid: 2681
hub_river_leaderboard:
  trustx:
    uid: 2682
  appnexus:
    placementId: 11726797
  ix:
    siteId: 213012
  rubiconLite:
    zoneId: 968556
  consumable:
    unitId: 5500
    unitName: cnsmbl-audio-728x90-slider
hub_river_med_rec:
  trustx:
    uid: 2684
  appnexus:
    placementId: 11726799
  ix:
    siteId: 213013
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
mobile_med_rec_athena:
  trustx:
    uid: 2685
  appnexus:
    placementId: 9883558
  ix:
    siteId: 186856
  rubicon:
    position: atf
  triplelift:
    inventoryCode: vox_midcontent_300x250_mobile
  rubiconLite:
    zoneId: 968556
    position: atf
  consumable:
    unitId: 5508
    unitName: cnsmbl-audio-300x250-slider
athena:
  appnexus:
    placementId: 9883544
  ix:
    siteId: 186850
  rubicon:
    position: atf
  rubiconLite:
    zoneId: 968556
    position: atf
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
btf_tablet_medium_rectangle:
  appnexus:
    placementId: 9883550
  ix:
    siteId: 186853
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
desktop_article_body:
  teads:
    placementId: 112919
  appnexus:
    placementId: 11726782
  ix:
    siteId: 213009
  rubiconLite:
    zoneId: 968556
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
in_map:
  appnexus:
    placementId: 11726796
  ix:
    disabled: true
  rubiconLite:
    zoneId: 968556
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
athena_features:
  appnexus:
    placementId: 11807799
  ix:
    siteId: 213014
  rubiconLite:
    zoneId: 968556
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
  teads:
    placementId: 112919
athena_features_dynamic:
  appnexus:
    placementId: 11807800
  ix:
    siteId: 213015
  rubiconLite:
    zoneId: 968556
  consumable:
    unitId: 5484
    unitName: cnsmbl-audio-300x250-slider
  teads:
    placementId: 112919
