---
- behavior: replace
- name: athena
  selector: ".hub-front-page .ad__athena_internal"
  sizes:
  - - 1030
    - 590
  holdSize:
  - 300
  - 295
  refreshEligible: false
  maxSlots: 1
- name: product-carousel
  selector: ".river-segment-0 .c-compact-river__entry:nth-child(3)"
  sizes:
  - - 1030
    - 590
  holdSize:
  - 300
  - 295
  refreshEligible: false
  maxSlots: 1
  insertion: after
- name: flyaway-conversations
  selector: ".river-segment-2 .c-compact-river__entry:nth-child(1)"
  sizes:
  - - 1030
    - 590
  holdSize:
  - 300
  - 295
  refreshEligible: false
  maxSlots: 1
  insertion: after
