---
biddingEnabled: true
prebidEnabled: true
timeout: 1000
amazonPubId: 3176
defaultConfig:
  openx:
    delDomain: sbnationbidder-d.openx.net
    unit: 540470346
  rubicon:
    accountId: 7470
    position: btf
    siteId: 225186
    zoneId: 1105274
  rubiconLite:
    accountId: 18288
    siteId: 193902
    sizes: [213, 270, 271, 272]
    position: btf
  rubi__mm:
    accountId: 21670
    siteId: 294140
    zoneName: "Mcelroy_MediaMath DC"
    zoneId: 1480276
  rubi__ttd:
    accountId: 21670
    siteId: 294142
    zoneName: "Mcelroy_TTD DC"
    zoneId: 1480302
prelude:
  trustx:
    uid: 2663
reskin:
  trustx:
    uid: 2664
desktop_leaderboard_variable:
  trustx:
    uid: 2665
  appnexus:
    placementId: 14508799
  rubicon:
    position: atf
medium_rectangle_variable:
  trustx:
    uid: 2666
  appnexus:
    placementId: 14508800
  rubicon:
    position: atf
btf_medium_rectangle_variable:
  trustx:
    uid: 2668
  appnexus:
    placementId: 14508801
desktop_article_medrec_dynamic:
  trustx:
    uid: 2669
  appnexus:
    placementId: 14508802
btf_leaderboard_variable:
  trustx:
    uid: 2670
  appnexus:
    placementId: 14508803
native_ad_latest:
  trustx:
    uid: 2671
native_ad_ymal_link:
  trustx:
    uid: 2672
mobile_leaderboard:
  trustx:
    uid: 2673
  appnexus:
    placementId: 14508804
  rubicon:
    position: atf
mobile_article_body:
  trustx:
    uid: 2674
  appnexus:
    placementId: 14508806
  rubiconLite:
    zoneId: 1105278
native_ad_mobile:
  trustx:
    uid: 2675
  appnexus:
    placementId: 14508807
  rubiconLite:
    zoneId: 1105278
mobile_article_body_med_rec_dynamic:
  trustx:
    uid: 2676
  appnexus:
    placementId: 14508808
  rubiconLite:
    zoneId: 1105278
mobile_footer:
  trustx:
    uid: 2677
  appnexus:
    placementId: 14508809
tablet_leaderboard:
  trustx:
    uid: 2678
  appnexus:
    placementId: 14508810
  rubicon:
    position: atf
tablet_btf_leaderboard:
  trustx:
    uid: 2680
  appnexus:
    placementId: 14508812
native_ad_content_link:
  trustx:
    uid: 2681
hub_river_leaderboard:
  trustx:
    uid: 2682
  appnexus:
    placementId: 14508814
  rubiconLite:
    zoneId: 1105278
hub_river_med_rec:
  trustx:
    uid: 2684
  appnexus:
    placementId: 14508815
mobile_med_rec_athena:
  trustx:
    uid: 2685
  appnexus:
    placementId: 14508816
  rubicon:
    position: atf
  rubiconLite:
    zoneId: 1105278
    position: atf
in_map:
  trustx:
    uid: 7313
  appnexus:
    placementId: 14508834
  rubiconLite:
    zoneId: 1105278
desktop_article_body:
  trustx:
    uid: 7312
  appnexus:
    placementId: 14508829
  rubiconLite:
    zoneId: 1105278
desktop_dynamic:
  trustx:
    uid: 7314
  appnexus:
    placementId: 14508825
desktop_athena_dynamic:
  trustx:
    uid: 7315
  appnexus:
    placementId: 14846211
  rubiconLite:
    zoneId: 1105278
tablet_medium_rectangle:
  trustx:
    disabled: true
